# Generated by Django 6.0 on 2026-01-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='spots/'),
        ),
    ]
